services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

  php:
    image: php:8.4-fpm
    volumes:
      - ~/Desktop/neom:/var/www/html:rw,cached  # Volume per la sincronizzazione del progetto locale con il container
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1 # Rende più rapido lo sviluppo, evita il recompilamento continuo
    working_dir: /var/www/html  # Directory di lavoro all'interno del container, corrispondente alla tua struttura locale
    depends_on:
      - database  # Il servizio PHP dipende dal database, assicurandosi che il database sia disponibile prima di avviare il PHP
