services:
  postgres:
    ports:
      - "5432:5432"

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  php:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "composer install && php -S 0.0.0.0:8000 -t public"
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}:/var/www/html:rw,cached
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    working_dir: /var/www/html
    depends_on:
      - postgres
      - mailer
